---
abstract: 'Depend on versions of modules the same as you have installed'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: '1.003001'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Module::Metadata: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::More: '0'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Prereqs-MatchInstalled
provides:
  Dist::Zilla::Plugin::Prereqs::MatchInstalled:
    file: lib/Dist/Zilla/Plugin/Prereqs/MatchInstalled.pm
    version: '1.001004'
recommends:
  Moose: '2.000'
requires:
  Dist::Zilla::Role::PrereqSource: '0'
  Dist::Zilla::Util::ConfigDumper: '0'
  Module::Data: '0'
  Moose: '0'
  MooseX::Types::Moose: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-MatchInstalled/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-MatchInstalled
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-MatchInstalled.git
version: '1.001004'
